### ISSUE TITLE
Incorrect argument parsing when "=" is part of the argument

### ISSUE THREAD

**Issue by borice** [sgmonda/stdio#5]
Given (coffeescript):

```
args = require("stdio").getopt
    meta:
        key: 'm'
        args: 1
        description: "The metadata file"
        mandatory: true
    features:
        key: 'f'
        args: 1
        description: "The features file"
        mandatory: true
```

If I run with:
`node merge.js -m loc.ark+=13960=t0000693r.meta.json -f loc.ark+=13960=t0000693r.feat.json`

the parsed command line looks like:

```
{ createHelp: [Function],
  printHelp: [Function],
  meta: 'loc.ark+=13960',
  args: [ 't0000693r.meta.json', 't0000693r.feat.json' ],
  features: 'loc.ark+=13960' }
```

But the file names are correct. One file is named `loc.ark+=13960=t0000693r.meta.json` and the other `loc.ark+=13960=t0000693r.feat.json`.  (I can't do anything about the names since they come out of another tool which parses what's called a "pairtree" directory structure).

The "=" sign in the filename is causing stdio to believe there's an assignment there when in fact it's not.  I tried escaping the = with \= but that didn't do anything.  I suggest adding another option to the configuration (in addition to "key", "args", "description"...etc.) like "decodeAssignment": true | false     (you can think of a better name for it)

-Boris
